ci: add a check for modules being linked correctly in the doc
A new module requires a \subpage entry in the respective parent page.
Check for that.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -281,6 +281,26 @@ spellcheck:
     - git ls-files | grep -v .gitlab-ci.yml | xargs -d '\n' sed -i 's/Pipewire/PipeWire/g'
     - git diff --exit-code || (echo "Please fix the above spelling mistakes" && exit 1)
 
+doccheck:
+  extends:
+    - .build_on_fedora
+  stage: analysis
+  script:
+    # Check that each media session module has a \subpage entry
+    - git grep -h -o -e "\\\page page_media_session_module_\w\+" | cut -f2 -d' ' > media_session_pages
+    - cat media_session_pages
+    - |
+      for page in $(cat media_session_pages); do
+          git grep -q -e "\\\subpage $page" || (echo "\\page $page is missing \\subpage entry in doc/media-session.dox" && false)
+      done
+    # Check that each pipewire module has a \subpage entry
+    - git grep -h -o -e "\\\page page_module_\w\+" | cut -f2 -d' ' > pipewire_module_pages
+    - cat pipewire_module_pages
+    - |
+      for page in $(cat pipewire_module_pages); do
+          git grep -q -e "\\\subpage $page" || (echo "\\page $page is missing \\subpage entry in doc/pipewire-modules.dox" && false)
+      done
+
 pages:
   extends:
     - .not_coverity
